---
- name: Get latest JetBrains Toolbox version information
  shell: |
    curl -s 'https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release' | jq -r '.TBA[0] | .build, .downloads.linux.link'
  register: toolbox_info

- name: Parse latest toolbox version and download link
  set_fact:
    toolbox_version: "{{ toolbox_info.stdout_lines[0] }}"
    toolbox_download_link: "{{ toolbox_info.stdout_lines[1] }}"
  when: not ansible_check_mode

- name: Download JetBrains Toolbox
  get_url:
    url: "{{ toolbox_download_link }}"
    dest: "/tmp/jetbrains-toolbox.tar.gz"
  when: not ansible_check_mode

- name: Create installation directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox"
    state: directory

- name: Extract JetBrains Toolbox
  unarchive:
    src: "/tmp/jetbrains-toolbox.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox"
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: not ansible_check_mode

- name: Ensure JetBrains Toolbox is executable
  command:
    cmd: chmod +x "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox/jetbrains-toolbox"

- name: Run JetBrains Toolbox
  command:
    cmd: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox/jetbrains-toolbox &"

- name: Wait for jetbrains-toolbox CLI to become available
  wait_for:
    path: "{{ ansible_env.HOME }}/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox"
    timeout: 30
